### ISSUE TITLE
Torque3D 3.7-RC - libogg fails to compile on Linux (OpenSUSE 13.2)

### ISSUE THREAD

**Issue by fr0zi** [GarageGames/Torque3D#1293]
System: OpenSUSE 13.2 (64-bit)
Build system: cmake, make (GCC 4.8)

I've got this error:

````
../Torque3D-3.7-rc/Engine/lib/libogg/include/ogg/os_types.h:143:32: fatal error: ogg/config_types.h: No such file or directory
````

It can be fixed by:
1. Download ogg library source from `http://www.xiph.org/downloads/`.
2. Compile it on your machine to create `config_types.h` from `config_types.h.in` file.
3. Copy `config_types.h` to `../Torque3D-3.7-rc/Engine/lib/libogg/include/ogg/`.
4. Compile Torque3D again.

**Comment by eightyeight** [comment]
Thanks for the steps. Do you think this is something we can fix by modifying Torque or using the platform layer differently? For now I'll add a note on the wiki about this. Which packages did you have to install to compile the engine? It'd be great if you could add it to the section [here](http://wiki.torque3d.org/coder:compiling-in-linux#toc1) about it, even if it's marked with some sort of warning.

**Comment by fr0zi** [comment]
I've added required packages section for OpenSUSE 13.2 on the wiki. 

Regarding the fix - I don't think any big change is necessary in Torque code. I figured out this issue can be fixed in three different ways:

* First way: by adding type definitions for Linux directly to `..Engine/lib/libogg/include/ogg/os_types.h` file like it is for other OSes in this file, so: 
```c++
// previous OS definitions

#elif defined(__GNUG__)

    /* GNU C++ compiler UNIX/LINUX */
#   include <sys/types.h>
#   include <inttypes.h>
#   include <stdint.h>
    typedef int16_t ogg_int16_t;
    typedef uint16_t ogg_uint16_t;
    typedef int32_t ogg_int32_t;
    typedef uint32_t ogg_uint32_t;
    typedef int64_t ogg_int64_t;
   
// we leave the rest of the file unchanged

#else

#  include <ogg/config_types.h>
```
* Second way: package libogg-devel contains the needed file `config_types.h` so it can be simply copied into `../Torque3D-3.7-rc/Engine/lib/libogg/include/ogg/` folder.

* Third way: the way I described at the beginning - downloading and compiling libogg from source from Vorbis homepage.

**Comment by eightyeight** [comment]
Thanks for that! It sounds like option number 1 makes it the simplest for users - am I right in thinking that means they could compile the engine without running into this issue? If we're doing that for other OSes already maybe we should follow suit. Can you see any downsides with this approach?

**Comment by Azaezel** [comment]
Actually, I'd really *really* suggest option 3, and chucking a copy in the main repo. Windows has taken to no longer including openal in their releases, so that'd be one more thing to package in a shipping build if we were to assume the game was the first one added to the end user's system.

**Comment by eightyeight** [comment]
So, compiling ogg into the engine rather than finding a library to link with dynamically? (This question may have betrayed my tiny tiny understanding of how this stuff actually works). Executable/DLL size increase?

**Comment by Azaezel** [comment]
As far as I'm aware, barring some very strange O/S setups indeed, so long as a dynamic lib sits alongside an executable, it'll look to that first before checking paths.

**Comment by eightyeight** [comment]
Ah, right, so you'd recommend compiling ogg/OAL libs to go next to the exe? Rather than compiling the code into the exe or engine DLL itself.

**Comment by Azaezel** [comment]
Seems the safest bet to ensure this kind of thing doesn't crop up again. (And if as folks have suggested a time or two we switch over to OpenAL Soft, we'd need to do so anyway at that point, since that one is LGPL)

**Comment by fr0zi** [comment]
Actually, I was also wondering if this is possible to put all the source code of ogg lib into Torque and compile it right next to the engine. It would generate this `config_types.h` file with the types specific to the machine - regardless if it's 32 or 64-bit. I didn't want to suggest any option since I don't know Torque source so well, but if this option is possible - I think it would be convenient and safe.
